### ISSUE TITLE
Allow cli to read geojson from stdin

### ISSUE THREAD

**Issue by jperelli** [jperelli/osm-static-maps#23]

**Comment by zag-adka** [comment]
I found your program because I wanted to generate PNG files for preview of a large set of GPS tracks. It's slow because of puppeteer using Chrome, started for each file. But it has done the job as I expected, with a very simple script. The only limitation was that for a few long tracks, I got this error:
/usr/local/bin/osmsm: Argument list too long

As your program wasn't able to work on an input file, I added this simple but useful feature.

**Comment by jperelli** [comment]
Cool @zag-adka, solved with your pull request and some other added things in https://github.com/jperelli/osm-static-maps/pull/26
